### ISSUE TITLE
plugin not working with inject: false

### ISSUE THREAD

**Issue by pavel06081991** [jouni-kantola/inline-chunk-manifest-html-webpack-plugin#3] opened 2017-04-03 18:14 UTC
I have such config for html-webpack-plugin:
```
new HtmlWebpackPlugin({
        template: './index.pug',
        inject: false,
```
and with inject: false inline-chunk-manifest-html-webpack-plugin does not work, it does not add manifest to head tag. What should I do for inline-chunk-manifest-html-webpack-plugin to work with inject: false?

**Comment by csentis** [comment] 2017-04-03 19:59
@pavel06081991 Must admit not to be familiar with the `inject: false` config. 

Could it be an idea for you to think about specifically not setting `inject: false`? In my case, these settings work out as I need them to work:

In e.g. webpack.config.js

```
    // ChunkHashPlugin
    // https://github.com/alexindigo/webpack-chunk-hash
    // https://webpack.js.org/guides/caching/
    new ChunkHashPlugin(),

    // Chunk Manifest Plugin
    // https://github.com/soundcloud/chunk-manifest-webpack-plugin
    new ChunkManifestPlugin({
        filename: 'chunks-manifest.json',
        manifestVariable: 'chunksManifest'
    }),

    // HtmlWebpackPlugin
    // https://github.com/ampedandwired/html-webpack-plugin
    new HtmlWebpackPlugin({
        [...]
        inject: true,
        [...]
    }),

    // InlineManifestHtmlWebpackPlugin
    // https://github.com/jouni-kantola/inline-chunk-manifest-html-webpack-plugin
    new InlineChunkManifestHtmlWebpackPlugin({
        filename: 'chunks-manifest.json',
        manifestVariable: 'chunksManifest'
    }),
```

Results in a chunks-manifest.json populated with...

```
{"0":"0.6de0471ef80696143c9c.js","1":"1.6de0471ef80696143c9c.js","2":"2.6de0471ef80696143c9c.js","3":"3.6de0471ef80696143c9c.js","4":"4.6de0471ef80696143c9c.js","5":"5.6de0471ef80696143c9c.js","6":"polyfills.6de0471ef80696143c9c.js","7":"vendor.6de0471ef80696143c9c.js","8":"app.6de0471ef80696143c9c.js"}
```

... and an index.html populated within the head tag with...

```
<script>window.chunksManifest={"0":"0.6de0471ef80696143c9c.js","1":"1.6de0471ef80696143c9c.js","2":"2.6de0471ef80696143c9c.js","3":"3.6de0471ef80696143c9c.js","4":"4.6de0471ef80696143c9c.js","5":"5.6de0471ef80696143c9c.js","6":"polyfills.6de0471ef80696143c9c.js","7":"vendor.6de0471ef80696143c9c.js","8":"app.6de0471ef80696143c9c.js"}</script>
```

In case this does not suit your use case:

my assumption would be that `inject: false` is set in case you have a placeholder/tag defined within your template where the (then not) injection should be resolved - is that correct?

If so, you might want to inspect whether [jaketrent/html-webpack-template](https://github.com/jaketrent/html-webpack-template) with its [index.ejs](https://github.com/jaketrent/html-webpack-template/blob/master/index.ejs) covers what you need (I propose you have a look at line 81 ff.).

**Comment by pavel06081991** [comment] 2017-04-03 20:16
> my assumption would be that inject: false is set in case you have a placeholder/tag defined within your template where the (then not) injection should be resolved - is that correct?

Yes, when inject: false - you should manually set placeholders where scripts and link tags will be placed. Here is example:

`link(rel="stylesheet" href=`${htmlWebpackPlugin.options.custom.assets.vendor.css}`)`

I'm not aware how to write plugins for webpack but when I saw sorce code of your plugin I thought that maybe it is possible to pass params to htmlWebpackPlugin for these params to be available inside ejs template(or pug or other template system)? If it is possible it would be great to add such opportunity for me and other people who use inject: false to be able to use these params in placeholders like this:

`<script>`${htmlWebpackPlugin.files.chunks.app.entry}`</script>`

How do you think it is possible or not? And thank you for your reply and help.

> If so, you might want to inspect whether jaketrent/html-webpack-template with its index.ejs covers what you need (I propose you have a look at line 81 ff.).

Unfortunately htmlWebpackPlugin object or any of its properties do not contain manifest, so now it is not possible to pass manifest to placeholder.

**Comment by csentis** [comment] 2017-04-03 21:04
@pavel06081991 Since this plugin is to a 100 % the work of @jouni-kantola let us see what he thinks of your proposals. Please excuse if I somehow mislead you to think of me as the author of this fine webpack plugin.

**Comment by pavel06081991** [comment] 2017-04-03 21:32
@csentis, okay, anyway thank you :)

**Comment by jouni-kantola** [comment] 2017-04-04 09:41
@pavel06081991: I didn't even know that option existed. I'm working on an update. Hopefully I'll have it up soon. Will reference the commit here.

**Comment by pavel06081991** [comment] 2017-04-04 09:42
@jouni-kantola, thanks!

**Comment by jouni-kantola** [comment] 2017-04-04 10:58
@pavel06081991 (and @csentis): I've now published a [v0.2.0](https://www.npmjs.com/package/inline-chunk-manifest-html-webpack-plugin). Instructions are updated.

The config is basically the same, but now can reference the chunk manifest in the `html-webpack-plugin` template like so:
`<%=htmlWebpackPlugin.files.webpackChunkManifest%>`

Please let me know if this works as intended and I'll close the issue afterwards.

**Comment by jouni-kantola** [comment] 2017-04-04 11:37
I'm now using the `inject: false` option myself. You can see my template here:
https://github.com/jouni-kantola/webpack-output-by-build-type/blob/master/tmpl/index.ejs

**Comment by pavel06081991** [comment] 2017-04-04 13:14
@jouni-kantola, thnak you very much! I'll check it soon.

**Comment by pavel06081991** [comment] 2017-04-04 13:46
Works great. Thanks one more time.

**Comment by jouni-kantola** [comment] 2017-04-04 13:48
@pavel06081991: Thank you for coming back after testing! This makes the plugin a lot more flexible as well, so thank you for letting me know that option exists.

Closing the issue.

**Closed as completed** 2017-04-04 13:49 UTC
